# Generated by Django 2.2.24 on 2022-10-25 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0004_auto_20221025_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=None, null=True, verbose_name='Новостройка'),
        ),
    ]
