# Generated by Django 2.2.24 on 2022-10-26 09:53

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('property', '0005_auto_20221025_1201'),
    ]

    operations = [
    ]



