# Generated by Django 2.2.24 on 2022-10-26 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0008_auto_20221026_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='new_building',
            field=models.BooleanField(default=None, null=True, verbose_name='Новостройка'),
        ),
    ]
