# Generated by Django 2.2.24 on 2022-10-27 03:25
import phonenumbers
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0015_auto_20221027_0606'),
    ]

    operations = [
    ]
