# Generated by Django 2.2.24 on 2022-10-27 05:55

from django.db import migrations


def migrate_owner(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    owner_model = apps.get_model('property', 'Owner')

    flats = flat_model.objects.all()

    for flat in flats.iterator():
        obj, created = owner_model.objects.get_or_create(
            name=flat.owner,
            owners_phonenumber=flat.owners_phonenumber,
            owner_pure_phone=flat.owner_pure_phone,
        )
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0019_auto_20221027_0747'),
    ]

    operations = [
        migrations.RunPython(migrate_owner),
    ]
