# Generated by Django 2.2.24 on 2022-10-28 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0020_auto_20221027_0855'),
    ]

    operations = [
    ]
