# Generated by Django 2.2.24 on 2022-10-28 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0021_auto_20221028_0513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='owner',
            field=models.CharField(db_index=True, max_length=200, verbose_name='ФИО владельца'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='name',
            field=models.CharField(db_index=True, max_length=250, verbose_name='ФИО владельца'),
        ),
    ]
