# Generated by Django 2.2.24 on 2022-10-28 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20221028_0557'),
    ]

    operations = [
    ]
