# Generated by Django 2.2.24 on 2022-10-28 02:58

from django.db import migrations


def migrate_owner_flats(apps, schema_editor):
    flat_model = apps.get_model('property', 'Flat')
    owner_model = apps.get_model('property', 'Owner')

    for owner in owner_model.objects.all():
        owner_flats = flat_model.objects.filter(owner=owner)
        print(owner_flats)
        owner.flats.set(owner_flats)
        owner.save()


def migrate_owner_flats_back(apps, schema_editor):
    owner_model = apps.get_model('property', 'Owner')

    for owner in owner_model.objects.all():
        owner.flats = None
        owner.save()


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0022_auto_20221028_0557'),
    ]

    operations = [
        migrations.RunPython(migrate_owner_flats, migrate_owner_flats_back),
    ]
