# Generated by Django 2.2.24 on 2022-10-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0025_auto_20221028_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='owner_flat', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
