# Generated by Django 2.2.24 on 2022-10-28 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0027_propertyownerownedflats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyOwnerOwnedFlats',
        ),
    ]
