# Generated by Django 2.2.24 on 2022-10-29 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0029_auto_20221029_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='owners_phonenumber',
            new_name='phonenumber',
        ),
        migrations.RenameField(
            model_name='owner',
            old_name='owner_pure_phone',
            new_name='pure_phone',
        ),
    ]
