# Generated by Django 2.2.24 on 2022-10-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0030_auto_20221029_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='flats',
            field=models.ManyToManyField(db_index=True, related_name='flats', to='property.Flat', verbose_name='Квартиры в собственности'),
        ),
    ]
