# Generated by Django 2.2.24 on 2022-11-03 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0033_auto_20221103_0752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaint',
            old_name='complaint_text',
            new_name='complaint',
        ),
    ]
